### ISSUE TITLE
typo3filepicker=..., encoding of "existing_files" is not according to specs

### ISSUE THREAD

**Issue by martinrode** [programmfabrik/typo3-easydb-plugin#17] opened 2020-08-31 08:01 UTC
Our specification document is here: https://docs.google.com/document/d/190-S4qwMvM_pFcJTHxZ9Zn7R_x7zcPelAraOlQONYo8/edit#

The list of existing files in the directory of the typo3 storage is transferred to easydb using an array of maps. For each existing file, we have `uid` as **key** and the *actual uid* as value.

Currently it looks like the PHP is transferring the Map like this:

```json
{
    "callbackurl": "https://.../...ra5b58357410d6c4a",
    "existing_files": [
        {
            "81d76d99-3c5f-4577-9908-6bc49d4270b6/549/3840_PX": "81d76d99-3c5f-4577-9908-6bc49d4270b6/549/3840_PX"
        },
        {
            "c3036859-22a2-4825-b74b-0775f01b532c/4635/3840_PX": "c3036859-22a2-4825-b74b-0775f01b532c/4635/3840_PX"
        },
        {
            "1bacd11a-3a8a-48ea-b9e5-419e3887181a/4638/3840_PX": "1bacd11a-3a8a-48ea-b9e5-419e3887181a/4638/3840_PX"
        },
        {
            "475efb70-f6dc-4824-8b79-f9004796e79e/4362/3840_PX": "475efb70-f6dc-4824-8b79-f9004796e79e/4362/3840_PX"
        },
```

This is **wrong**.

It needs to look like this:

 ```json
{
    "callbackurl": "https://redaktion.hhu.de/typo3/index.php?route=%2Fajax%2Feasydb%2Fimport&id=1%3A%2Fredaktion%2FZUV%2FDezernat_1%2FStudierenden_Service_Center%2FStudienberatungsportal%2F&importToken=0db2e6759454f1eb5c3b98a1a5b58357410d6c4a",
    "existing_files": [
        {
            "uid": "81d76d99-3c5f-4577-9908-6bc49d4270b6/549/3840_PX"
        },
        {
            "uid": "c3036859-22a2-4825-b74b-0775f01b532c/4635/3840_PX"
        },
        {
            "uid": "1bacd11a-3a8a-48ea-b9e5-419e3887181a/4638/3840_PX"
        },
        {
            "uid": "475efb70-f6dc-4824-8b79-f9004796e79e/4362/3840_PX"
        },
```

It is very curious that we have not noticed this earlier!

**Comment by helhum** [comment] 2020-09-01 07:46
This is a duplicate of #11 and fixed with 9435229. But for some reason was never released. Will release it now.

**Closed by helhum** 2020-09-01 07:46 UTC
Labels: bug
