### ISSUE TITLE
Multi language support does not work

### ISSUE THREAD

**Issue by datango** [programmfabrik/typo3-easydb-plugin#5] opened 2019-01-31 13:33 UTC
a) It works, if i use a standard TYPO3 installation with introduction package (8.7.24) for the field title. It does not get the static string from mapping for field desciption.

b) It does not work in our productive/development enviroment (8.7.24)

We have three languages configured in addition to default :
    de
    en
    zh 
We use different default languages on different hosts and sites changed by Typoscript.

On both systems I configured de-DE as the default language in the easydb plugin. In System b) I get no data stored in the meta data fields at all. They are all empty. A german (non default) translation was created. I get the following error in the log: Attempt to modify table 'sys_file_metadata' without permission (msg#1.2.1) 

Array metaDataUpdates in mapEasydbMetaDataToMetaDataRecords contains data like this:

```
{

    "336447":{
        "title":"Demo1234"
    },
    "0":{
        "title":"Demo5678"
    },
    "336446":{
        "description":""
    }

}
```

```
Locale Array as JSON:

{"de-DE":1,"zh-CN":13,"en-US":11}
```

Our language configs:
![grafik](https://user-images.githubusercontent.com/30523869/52056370-57b4cc00-2562-11e9-8c4b-3c21abae0806.png)

System environment:

Debian Stretch mit
PHP 7.0.33
MySQL 5.5.5
Apache 

What i want to accomplish:
DE as default
EN as extra language
DE empty
ZH empty

It could be good to also write default language data (DE) to DE.

EasyDB:

Data model:
![grafik](https://user-images.githubusercontent.com/30523869/52057102-6ef4b900-2564-11e9-8aa1-a82627a7336e.png)

Screenshot example data:
![grafik](https://user-images.githubusercontent.com/30523869/52057041-4c62a000-2564-11e9-8637-167ca78b8490.png)

Mapping:
![grafik](https://user-images.githubusercontent.com/30523869/52057269-e591b680-2564-11e9-8a0e-06bb9e39fd9b.png)

**Comment by helhum** [comment] 2019-02-01 15:17
Thanks for the report!

> We use different default languages on different hosts and sites changed by Typoscript.

Without going into details, I think this is the main culprit here. For files, languages are global, and there can only be one language (locale) defined as default.

> We have three languages configured in addition to default: de, en, zh

Can you post the easydb locales you configured for default (you mentioned `de-DE` is this correct?) **and** the locales configured in *each* language record?

Thanks.

**Comment by helhum** [comment] 2019-02-01 15:18
Ah, sorry, saw the screenshot. So you have `de-DE` configured twice. I will check if I can reproduce the error with such configuration.

**Comment by helhum** [comment] 2019-04-05 20:36
@datango can you check whether the referenced change fixes your issue?

What I changed there is:

Meta data is now only imported into TYPO3 languages, the current user has access to.
This should fix the error message `Attempt to modify table 'sys_file_metadata' without permission` you are seeing.

Additionally, meta data is imported into the default language as well, even when the locale defined for it is also defined for another TYPO3 language.

**Comment by helhum** [comment] 2019-08-26 10:40
duplicate of #6

**Closed by helhum** 2019-08-26 10:40 UTC
